#!/bin/bash

cd uncompiled-packages/
rm .DS_Store
cd co.quartzy.beta
rm .DS_Store
cd Library
rm .DS_Store
cd Themes
rm .DS_Store
cd Quartzy-color.theme
rm .DS_Store
cd ..
cd Quartzy-dark.theme
rm .DS_Store
cd ..
cd Quartzy-glyph.theme
rm .DS_Store
cd ..
